### ISSUE TITLE
Toepasbare regels voor PLAATSEN ZONNEPANELEN

### ISSUE THREAD

**Issue by DevlinOosterwijk** [IDgis/Hengelo#6]

**Comment by Fleurwolthuis** [comment]
Het plaatsen van zonnepanelen betreft één activiteit. Het gaat hier om artikel 2 van bijlage II bij het Besluit omgevingsrecht, aangevuld met artikel 4a van bijlage II bij het Bor, waarin het stads- en dorpsgezicht is opgenomen. Hiervoor gelden aanvullende voorschriften. Hier hebben wij onze toepasbare regels op gebaseerd.

Bij het vullen van de activiteit wilden we andere werkzaamheden hieraan toevoegen, maar dat is ons niet gelukt. Vraag voor Sila.
We hebben de activiteit gecheckt en volgens ons is het proces nu goed opgenomen. We hebben geen begin gemaakt met het aanvraagformulier.
