### ISSUE TITLE
Toepasbare regels voor AANLEGGEN UITRIT

### ISSUE THREAD

**Issue by DevlinOosterwijk** [IDgis/Hengelo#7]

**Comment by Fleurwolthuis** [comment]
We hebben er voor gekozen om het maken van een uitweg en het veranderen van een uitweg in twee aparte activiteiten op te nemen in de STTR Builder. Na overleg met Sila, was het misschien toch handiger geweest om deze twee activiteiten samen te voegen. We hebben ook de weigeringsgronden opgenomen in de STTR Builder, wat officieel niet nodig is. Omdat we anders met één vraag al klaar waren, hebben we deze als oefening opgenomen.
De artikelen over de uitwegen zijn opgenomen in de APV. Hier hebben wij onze toepasbare regels op gebaseerd.
Bij het vullen van de activiteit wilden we andere werkzaamheden hieraan toevoegen, maar dat is ons niet gelukt. Vraag voor Sila.
We hebben de activiteit gecheckt en volgens ons is het proces nu goed opgenomen. We hebben een begin gemaakt met het meldingsformulier.
